### PR TITLE
Add the ability for the loading and error override components to be dynamic based on the current document

### PR DESCRIPTION
**Pull request by jonphil18**
Demo file and README have also been updated

### CODE REVIEW

**Review by cyntler — APPROVED** [review]

**Comment by cyntler** [comment]
@jonphil18 Thanks for your PR!

**Comment by jonphil18** [comment]
> 

No problem. Any idea when the next minor release will be? Would love to get this included in my project.

**Comment by cyntler** [comment]
@jonphil18 Done.

**Comment by jonphil18** [comment]
Thanks!

**Pull request merged**
