### PR TITLE
Add serbian lat and Cyrillic

### PR DESCRIPTION
**Pull request by damirkoDamdza**

### CODE REVIEW

**Review by cyntler — APPROVED** [review]
👍

**Comment by cyntler** [comment]
@damirkoDamdza Merged. Thank you!

**Comment by damirkoDamdza** [comment]
Hello Cyntler,

Can you update npm package @cyntler/react-doc-viewer, because I used this library in project and I would like to see that translations work?

**Comment by damirkoDamdza** [comment]
Thanks in advanced :)

**Comment by cyntler** [comment]
@damirkoDamdza Released but without fixes in serbian locales. It will be released at the next version tomorrow or next days.

**Pull request merged**
